security:
    providers:
        webservice:
            id: App\Security\User\UserProvider
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        !php/const App\Entity\User::ROLE_USER: ~
        !php/const App\Entity\User::ROLE_EMPLOYEE: !php/const App\Entity\User::ROLE_USER
        !php/const App\Entity\User::ROLE_ADMIN: !php/const App\Entity\User::ROLE_USER
        !php/const App\Entity\User::ROLE_SUPER_ADMIN: !php/const App\Entity\User::ROLE_ADMIN

    access_control:
        -   path: ^/$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -   path: ^/ban_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_SUPER_ADMIN
            methods: [POST, PUT, DELETE]
        -   path: ^/ban_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/business_trip_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/configs
            methods: [GET]
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/configs
            methods: [POST]
            roles:
                - !php/const App\Entity\User::ROLE_SUPER_ADMIN
        -   path: ^/home_office_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/maternity_protection_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_SUPER_ADMIN
            methods: [POST, PUT, DELETE]
        -   path: ^/maternity_protection_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/overtime_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/parental_leave_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_SUPER_ADMIN
            methods: [POST, PUT, DELETE]
        -   path: ^/parental_leave_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/sick_day_unpaid_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_SUPER_ADMIN
            methods: [POST, PUT, DELETE]
        -   path: ^/sick_day_unpaid_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/sick_day_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/special_approvals/[0-9]+'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/special_leave_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/time_off_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/supervised_users$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/api_token'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/users/api_token
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/vacations'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/work_hours$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN

        -   path: '^/users/[0-9]+/work_months$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/users
            roles:
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/vacation_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/vacations
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/work_hours
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/work_months/[0-9]+/set_work_time_correction'
            roles:
                - !php/const App\Entity\User::ROLE_SUPER_ADMIN
        -   path: ^/work_months
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/logout,
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
