App\Entity\SpecialLeaveWorkLog:
    attributes:
        id:
            groups:
                - special_leave_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        date:
            groups:
                - special_leave_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - special_leave_work_log_in
        timeApproved:
            groups:
                - special_leave_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        timeRejected:
            groups:
                - special_leave_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
        rejectionMessage:
            groups:
                - special_leave_work_log_out_detail
                - special_approvals_out_list
                - work_month_out_detail
                - special_leave_work_log_in
        workMonth:
            groups:
                - special_leave_work_log_out_detail
                - special_approvals_out_list
