#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /login_check
    methods: [POST]

api_logout:
    path: /logout
    methods: [POST]

api_reset_password:
    path: /reset-password
    methods: [PUT]
    controller: App\Controller\UserController::resetPassword
    defaults:
        _api_collection_operation_name: 'resetPassword'

api_new_password:
    path: /new-password
    methods: [PUT]
    controller: App\Controller\UserController::newPassword
    defaults:
        _api_collection_operation_name: 'newPassword'

api_business_trip_work_log_mark_approved:
    path: /business_trip_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\BusinessTripWorkLogController::markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_business_trip_work_log_mark_rejected:
    path: /business_trip_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\BusinessTripWorkLogController::markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_config_get:
    path: /configs
    methods: [GET]
    controller: App\Controller\ConfigController::getConfig
    defaults:
        _api_collection_operation_name: 'getConfig'

api_config_save:
    path: /configs
    methods: [POST]
    controller: App\Controller\ConfigController::saveConfig
    defaults:
        _api_collection_operation_name: 'saveConfig'

api_home_office_work_log_mark_approved:
    path: /home_office_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\HomeOfficeWorkLogController::markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_home_office_work_log_mark_rejected:
    path: /home_office_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\HomeOfficeWorkLogController::markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_maternity_protection_work_log_bulk_create:
    path: /maternity_protection_work_logs/bulk
    methods: [POST]
    controller: App\Controller\MaternityProtectionWorkLogController::bulkCreate
    defaults:
        _api_collection_operation_name: 'bulkCreate'

api_overtime_work_log_mark_approved:
    path: /overtime_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\OvertimeWorkLogController::markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_overtime_work_log_mark_rejected:
    path: /overtime_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\OvertimeWorkLogController::markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_parental_leave_work_log_bulk_create:
    path: /parental_leave_work_logs/bulk
    methods: [POST]
    controller: App\Controller\ParentalLeaveWorkLogController::bulkCreate
    defaults:
        _api_collection_operation_name: 'bulkCreate'

api_sick_day_unpaid_work_log_bulk_create:
    path: /sick_day_unpaid_work_logs/bulk
    methods: [POST]
    controller: App\Controller\SickDayUnpaidWorkLogController::bulkCreate
    defaults:
        _api_collection_operation_name: 'bulkCreate'

api_special_leave_work_log_bulk_create:
    path: /special_leave_work_logs/bulk
    methods: [POST]
    controller: App\Controller\SpecialLeaveWorkLogController::bulkCreate
    defaults:
        _api_collection_operation_name: 'bulkCreate'

api_special_leave_work_log_bulk_mark_approved:
    path: /special_leave_work_logs/bulk/mark_approved
    methods: [PUT]
    controller: App\Controller\SpecialLeaveWorkLogController::bulkMarkApproved
    defaults:
        _api_collection_operation_name: 'bulkMarkApproved'

api_special_leave_work_log_bulk_mark_rejected:
    path: /special_leave_work_logs/bulk/mark_rejected
    methods: [PUT]
    controller: App\Controller\SpecialLeaveWorkLogController::bulkMarkRejected
    defaults:
        _api_collection_operation_name: 'bulkMarkRejected'

api_special_leave_work_log_mark_approved:
    path: /special_leave_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\SpecialLeaveWorkLogController::markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_special_leave_work_log_mark_rejected:
    path: /special_leave_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\SpecialLeaveWorkLogController::markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_time_off_work_log_mark_approved:
    path: /time_off_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\TimeOffWorkLogController::markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_time_off_work_log_mark_rejected:
    path: /time_off_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\TimeOffWorkLogController::markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_vacation_work_log_bulk_create:
    path: /vacation_work_logs/bulk
    methods: [POST]
    controller: App\Controller\VacationWorkLogController::bulkCreate
    defaults:
        _api_collection_operation_name: 'bulkCreate'

api_vacation_work_log_bulk_mark_approved:
    path: /vacation_work_logs/bulk/mark_approved
    methods: [PUT]
    controller: App\Controller\VacationWorkLogController::bulkMarkApproved
    defaults:
        _api_collection_operation_name: 'bulkMarkApproved'

api_vacation_work_log_bulk_mark_rejected:
    path: /vacation_work_logs/bulk/mark_rejected
    methods: [PUT]
    controller: App\Controller\VacationWorkLogController::bulkMarkRejected
    defaults:
        _api_collection_operation_name: 'bulkMarkRejected'

api_vacation_work_log_mark_approved:
    path: /vacation_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\VacationWorkLogController::markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_vacation_work_log_mark_rejected:
    path: /vacation_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\VacationWorkLogController::markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_users_renew_api_token:
    path: /users/{id}/api_token/renew
    methods: [PUT]
    controller: App\Controller\UserController::renewApiToken
    defaults:
        _api_collection_operation_name: 'renewApiToken'

api_users_reset_api_token:
    path: /users/{id}/api_token/reset
    methods: [PUT]
    controller: App\Controller\UserController::resetApiToken
    defaults:
        _api_collection_operation_name: 'resetApiToken'

api_users_by_api_token:
    path: /users/api_token/{apiToken}
    methods: [GET]
    controller: App\Controller\UserController::getUserByApiToken
    defaults:
        _api_collection_operation_name: 'getUserByApiToken'

api_supervised_users:
    path: /users/{id}/supervised_users
    methods: [GET]
    controller: App\Controller\UserController::supervisedUsers
    defaults:
        _api_collection_operation_name: 'supervisedUsers'

api_work_months_detail:
    path: /work_months/{id}/detail
    methods: [GET]
    controller: App\Controller\WorkMonthController::getWorkMonthDetail
    defaults:
        _api_collection_operation_name: 'getWorkMonthDetail'

api_work_months_special_approvals:
    path: /special_approvals/{supervisorId}
    methods: [GET]
    controller: App\Controller\WorkMonthController::specialApprovals
    defaults:
        _api_collection_operation_name: 'specialApprovals'

api_work_months_recent_special_approvals:
    path: /recent_special_approvals/{supervisorId}
    methods: [GET]
    controller: App\Controller\WorkMonthController::recentSpecialApprovals
    defaults:
        _api_collection_operation_name: 'recentSpecialApprovals'

api_work_months_mark_approved:
    path: /work_months/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\WorkMonthController::markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_work_months_mark_waiting_for_approval:
    path: /work_months/{id}/mark_waiting_for_approval
    methods: [PUT]
    controller: App\Controller\WorkMonthController::markWaitingForApproval
    defaults:
        _api_collection_operation_name: 'markWaitingForApproval'

api_work_months_set_work_time_correction:
    path: /work_months/{id}/set_work_time_correction
    methods: [PUT]
    controller: App\Controller\WorkMonthController::setWorkTimeCorrection
    defaults:
        _api_collection_operation_name: 'setWorkTimeCorrection'
