App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - App\Validator\Constraints\WorkHoursPresent: ~
    properties:
        email:
            - NotBlank: ~
            - Email:
                mode: strict

        employeeId:
            - NotBlank: ~
            - Length:
                min: 1
                max: 200

        firstName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 200

        lastName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 200

        plainPassword:
            - NotBlank:
                groups:
                    - user_password_required
            - Length:
                min: 8

        vacationDays:
            - NotBlank: ~
            - Range:
                min: 0

        workHours:
            - Valid: ~
