App\Entity\WorkHours:
    properties:
        year:
            - Valid: ~

        month:
            - NotBlank: ~
            - Type: int
            - Range:
                min: 1
                max: 12

        requiredHours:
            - NotBlank: ~
            - Type: numeric
            - Range:
                min: 0
                max: 24

        user:
            - NotBlank: ~