App\Entity\BusinessTripWorkLog:
    type: entity

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        date:
            type: datetime_immutable
        purpose:
            type: text
        destination:
            type: text
        transport:
            type: text
        expectedDeparture:
            type: text
        expectedArrival:
            type: text
        timeApproved:
            type: datetime_immutable
            nullable: true
        timeRejected:
            type: datetime_immutable
            nullable: true
        rejectionMessage:
            type: text
            nullable: true

    manyToOne:
        workMonth:
            targetEntity: App\Entity\WorkMonth
            inversedBy: businessTripWorkLogs
            joinColumn:
                name: work_month_id
                referencedColumnName: id
                nullable: false
