App\Entity\User:
    type: entity
    table: app_user

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        email:
            type: text
            unique: true

        employeeId:
            type: text
            unique: true

        firstName:
            type: text

        lastName:
            type: text

        password:
            type: text

        isActive:
            type: boolean

        roles:
            type: json_array

        resetPasswordToken:
            type: text
            nullable: true

        apiToken:
            type: text
            unique: true
            nullable: true

    oneToMany:
        vacations:
            targetEntity: App\Entity\Vacation
            mappedBy: user
            cascade: [persist]
        workHours:
            targetEntity: App\Entity\WorkHours
            mappedBy: user
            cascade: [persist]
        workMonths:
            targetEntity: App\Entity\WorkMonth
            mappedBy: user
        yearStats:
            targetEntity: App\Entity\UserYearStats
            mappedBy: user

    manyToOne:
        supervisor:
            targetEntity: App\Entity\User
            mappedBy: supervised
            joinColumn:
                name: supervisor_id
                referencedColumnName: id
                onDelete: SET NULL
                nullable: true
